sudo: required

services:
  - docker

language: java

jdk:
  - openjdk8

env:
  matrix:
   - RC_VERSION=latest
   - RC_VERSION=develop
   - RC_VERSION=2.4.7
   - RC_VERSION=2.3.3
   - RC_VERSION=2.2.1
   - RC_VERSION=2.1.3
   - RC_VERSION=2.0.0
   - RC_VERSION=1.3.2
   - RC_VERSION=1.2.1
   - RC_VERSION=1.1.3
   - RC_VERSION=1.0.3
   - RC_VERSION=0.74.3

script:
  - mvn clean package --quiet
  - .bin/docker-build-images.sh && .bin/docker-run.sh
  - travis_retry mvn -Pdocker -Djava.awt.headless=true -Dmaven.test.redirectTestOutputToFile=true -Dcobertura.report.format=xml --fail-at-end --batch-mode cobertura:cobertura verify

cache:
  directories:
  - ~/.m2

after_success:
  - cobertura:dump-datafile
  - bash <(curl -s https://codecov.io/bash)


install:
  -
